name: Downstream Job

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
      commit_id:
        required: true
        type: string
      pr_link:
        required: true
        type: string
      repo_name:
        required: true
        type: string

jobs:
  downstream:
    runs-on: windows-latest

    steps:
      - name: Print Received Inputs
        shell: pwsh
        run: |
          Write-Host "Branch: ${{ inputs.branch }}"
          Write-Host "Commit: ${{ inputs.commit_id }}"
          Write-Host "PR: ${{ inputs.pr_link }}"
          Write-Host "Repo: ${{ inputs.repo_name }}"

      - name: Simple Step Example
        shell: pwsh
        run: |
          Write-Host "Doing some downstream work..."
          Start-Sleep -Seconds 5
          Write-Host "Downstream completed."
